name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - run: pip install -r requirements-dev.txt
      - run: pytest -v

  sast:
    name: SAST (bandit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install bandit==1.9.4
      - run: bandit -r app run.py -f txt -o bandit-report.txt --severity-level medium
      - run: cat bandit-report.txt
        if: always()
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-report
          path: bandit-report.txt

  sca:
    name: SCA (pip-audit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pip-audit==2.10.1
      - run: pip-audit -r requirements.txt --desc | tee pip-audit-report.txt
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pip-audit-report
          path: pip-audit-report.txt

  dependency-check:
    name: SCA (OWASP Dependency-Check)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dependency-check/Dependency-Check_Action@main
        with:
          project: lab1-secure-api
          path: .
          format: HTML
          args: --enableExperimental --failOnCVSS 7 --suppression dependency-check-suppressions.xml
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: reports
